services:
  primary:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - od_prom_net
    healthcheck:
      test: 'pg_isready -U postgres --dbname=postgres'
      interval: 1s
      timeout: 1s
      retries: 3

  prometheus:
    image: prom/prometheus:main
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - od_prom_net
    depends_on:
      - odyssey

  odyssey:
    init: true
    build:
      dockerfile: ./docker/prometheus-legacy/Dockerfile
      context: ../../ # odyssey root dir
      args:
        odyssey_build_type: "${ODYSSEY_PROM_BUILD_TYPE:-build_dbg}"
    ports:
      - "6432:6432"
      - "7777:7777"
    networks:
      - od_prom_net
    depends_on:
      - primary

networks:
  od_prom_net:
    driver: bridge