name: Build on alpine
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  alpine-build:
    name: alpine-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Odyssey build on alpine test
      run: make ody_quickstart_test
